- name: Generate SSH keys
  shell: ssh-keygen -b 2048 -t rsa -f /home/{{ ansible_user }}/.ssh/id_ocp -q -N ""
  args:
    creates: /home/{{ ansible_user }}/.ssh/id_ocp

- name: Generate SSH pub key
  shell: ssh-keygen -y -f /home/{{ ansible_user }}/.ssh/id_ocp > /home/{{ ansible_user }}/.ssh/id_ocp.pub
  args:
    creates: /home/{{ ansible_user }}/.ssh/id_ocp.pub

- name: Slurp public key
  slurp:
    path: /home/{{ ansible_user }}/.ssh/id_ocp.pub
  register: idrsapub

- name: Create cluster directory
  file:
    path: /home/{{ ansible_user }}/{{ cluster_name }}
    state: directory

- name: Use default template for install-config-yaml
  set_fact:
    install_config_template_path: templates/install-config.yaml.j2

- name: Generate config install-config.yaml
  template:
    src: "{{ install_config_template_path }}"
    dest: /home/{{ ansible_user }}/{{ cluster_name }}/install-config.yaml
    owner: "{{ ansible_user }}"
    mode: 0660

- name: Make a copy of the cluster install config
  copy:
    remote_src: true
    src: /home/{{ ansible_user }}/{{ cluster_name }}/install-config.yaml
    dest: /home/{{ ansible_user }}/{{ cluster_name }}/install-config.yaml.bak
    owner: "{{ ansible_user }}"
    mode: 0660
